### PR TITLE
Upgrade Angular 5.1.2, Angular 1.6.3, Material 5.0.3 etc

### PR DESCRIPTION
**Pull request by yogeshgadge**
blocked from upgrading due to https://github.com/angular/angular-cli/issues/9061 and its PR not yet released

### CODE REVIEW

**Comment by walhow** [comment]
Does this fix the issue with `ng generate`?

**Comment by yogeshgadge** [comment]
@walhow Yes it fixes ng generate issue however in order to merge this I need angular cli 1.6.4 version which is not released yet. This is just to avoid one roboto/fontawesome workaround which is broken in 1.6.3.

**Comment by yogeshgadge** [comment]
Will remove workaround later.

**Comment by cgatian** [comment]
FYI I downgraded to Angular CLI 1.5.4 and it worked.

**Comment by yogeshgadge** [comment]
The new release 2.1.2 fixes this with CLI 1.6.3.

**Pull request merged**
